if: type = pull_request

language: node_js

git:
  depth: 3

node_js:
  - '10.15.0'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn global add lerna jest
  - yarn bootstrap

script:
  - yarn lint
  - yarn build
  - yarn test
